version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - sfdx-6.8.2-local
      - run:
          name: Install Salesforce DX
          command: |
            openssl aes-256-cbc -k $KEY -in assets/server.key.enc -out assets/server.key -d -md sha256
            if [ ! -d node_modules/sfdx-cli ]; then
                export SFDX_AUTOUPDATE_DISABLE=true
                export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
                export SFDX_DOMAIN_RETRY=300
                npm install sfdx-cli@6.8.2
                node_modules/sfdx-cli/bin/run --version
                node_modules/sfdx-cli/bin/run plugins --core
            fi
      - save_cache:
          key: sfdx-6.8.2-local
          paths:
            - node_modules
      - run:
          name: Create Scratch Org
          command: |
            node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a DevHub
            node_modules/sfdx-cli/bin/run force:org:create -v DevHub -s -f config/project-scratch-def.json -a scratch
      - run:
          name: Push Source
          command: |
            node_modules/sfdx-cli/bin/run force:source:push -u scratch
      - run:
          name: Run Apex Tests
          command: |
            mkdir ~/tests
            mkdir ~/tests/apex
            node_modules/sfdx-cli/bin/run force:apex:test:run -u scratch -c -r human -d ~/tests/apex -w 9999
      - run:
          name: Clean Up
          when: always
          command: |
            node_modules/sfdx-cli/bin/run force:org:delete -u scratch -p
            rm ~/tests/apex/*.txt ~/tests/apex/test-result-7*.json
            rm assets/server.key
      - store_artifacts:
          path: ~/apex_tests
      - store_test_results:
          path: ~/apex_tests

  deploy-prod:
    docker:
      - image: circleci/openjdk:latest-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - sfdx-6.8.2-local
      - run:
          name: Install Salesforce DX
          command: |
            openssl aes-256-cbc -k $KEY -in assets/server.key.enc -out assets/server.key -d -md sha256
            if [ ! -d node_modules/sfdx-cli ]; then
                export SFDX_AUTOUPDATE_DISABLE=true
                export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
                export SFDX_DOMAIN_RETRY=300
                npm install sfdx-cli@6.8.2
                node_modules/sfdx-cli/bin/run --version
                node_modules/sfdx-cli/bin/run plugins --core
            fi
      - save_cache:
          key: sfdx-6.8.2-local
          paths:
            - node_modules
      - run:
          name: Log in Org
          command: |
            node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a DevHub
      - run:
          name: Remove Server Key
          when: always
          command: |
            rm assets/server.key
      - run:
          name: Converting to MDAPI format...
          command: |
            node_modules/sfdx-cli/bin/run force:source:convert -d deploy_prod -r force-app
      - run:
          name: Deploying to production & running all tests...
          command: |
            node_modules/sfdx-cli/bin/run force:mdapi:deploy -u DevHub -d deploy_prod/ -w -1 -l RunAllTestsInOrg
      - store_artifacts:
          path: ~/apex_tests
      - store_test_results:
          path: ~/apex_tests

workflows:
  version: 2
  validate:
    jobs:
      # - build:
      #     filters:
      #       branches:
      #         ignore:
      #           - master
      - deploy-prod:
          filters:
            branches:
              only:
               # - master
