version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - sfdx-6.8.2-local
      - run:
          name: Install Salesforce DX
          command: |
            openssl aes-256-cbc -k $KEY -in assets/server.key.enc -out assets/server.key -d -md sha256
            if [ ! -d node_modules/sfdx-cli ]; then
                export SFDX_AUTOUPDATE_DISABLE=true
                export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
                export SFDX_DOMAIN_RETRY=300
                npm install sfdx-cli@6.8.2
                node_modules/sfdx-cli/bin/run --version
                node_modules/sfdx-cli/bin/run plugins --core
            fi
      - save_cache:
          key: sfdx-6.8.2-local
          paths:
            - node_modules
      - run:
          name: Create Scratch Org
          command: |
            node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a DevHub
      - run:
          name: Remove Server Key
          when: always
          command: |
            rm assets/server.key
      - run:
          name: Converting to MDAPI format...
          command: |
            node_modules/sfdx-cli/bin/run sfdx force:source:convert -d deploy_prod -r force-app
      - run:
          name: Deploying to production & running all tests...
          command: |
            node_modules/sfdx-cli/bin/run sfdx force:mdapi:deploy -u DevHub -d deploy_prod/ -w -1 -l RunAllTestsInOrg
      - store_artifacts:
          path: ~/apex_tests
      - store_test_results:
          path: ~/apex_tests
